### ISSUE TITLE
Need support dvorak keyboard

### ISSUE THREAD

**Issue by JohnnySun** [BMY-Soft/Kestrel-Kernel#2]
I think we need support dvorak keyboard.

**Comment by JohnnySun** [comment]
Closed #2

**Comment by JohnnySun** [comment]
resolved

**Comment by M0xkLurk3r** [comment]
Low-power make a qwerty keyboard into a dvorak keyboard recently...

**Comment by Low-power** [comment]
Neusoft to Google proxy just restored

**Comment by JohnnySun** [comment]
@M0xkLurk3r ,Has invited you as developer

**Comment by JohnnySun** [comment]
@M0xkLurk3r yep, @Low-power had make a "',.pyf"(“qwerty") version for kestrel. this 1.0a3 version is add Dvorak support.

**Comment by JohnnySun** [comment]
@M0xkLurk3r 23333333 @Low-power make that keyboard~~~~ But i had a Dvorak laptop :)
