### ISSUE TITLE
KEY "[ ]" & "{ }" have bug on Dvorak keyboard

### ISSUE THREAD

**Issue by JohnnySun** [BMY-Soft/Kestrel-Kernel#4]
Can't input KEY "[ ]" & "{ }"

**Comment by JohnnySun** [comment]
#2 still have bug.

**Comment by Low-power** [comment]
Resolved

2015-01-05 0:31 GMT+08:00 JohnnySun <notifications@github.com>:

**Comment by JohnnySun** [comment]
Thanks, Good work.
